### ISSUE TITLE
how can i loader pcd files with the WWOBJLoader

### ISSUE THREAD

**Issue by huanmie913** [kaisalmen/WWOBJLoader#10]
hi, @kaisalmen , i'm so glad to see your page;
i want to load pcd files with WWOBJLoader and the PcdLoader 
but i don't know how use this plugin,
could you give me some suggestion?
thanks a lot

**Comment by kaisalmen** [comment]
Hi @huanmie913, I am currently working on separating the provision of mesh data within a worker from the actual file format to open it up for other file formats: See this branch:
https://github.com/kaisalmen/WWOBJLoader/tree/Commons
And this demo:
https://github.com/kaisalmen/WWOBJLoader/tree/Commons/test/meshspray

**Comment by kaisalmen** [comment]
This will be discussed in issue #11

**Comment by huanmie913** [comment]
@kaisalmen ,thanks a lot;
you're a nice person;
i'll just to try;
tks again.

**Comment by kaisalmen** [comment]
@huanmie913 I will provide you with some hints. Sorry, spare time was very limited the last couple of weeks.

The code on the bespoke branch may still change substantially that's why any new loader implementation may require change in the future. The idea is to open the mechanism to other file formats (not only OBJ and PCD)

I would like to discuss my approach and receive feedback from other three.js devs that's why I opened the other issue.

**Comment by kaisalmen** [comment]
Required changes are in place. I will start this as soon as there is time.

**Comment by kaisalmen** [comment]
@huanmie913 it took a while, but here is the first working prototype:
https://kaisalmen.de/proto/test/pcd/webgl_loader_pcd.html

**Comment by kaisalmen** [comment]
I extracted the main changes to the master branch and force pushed the branch related to this issue only containing the changes related to PCDLoader.

**Comment by kaisalmen** [comment]
Fully implemented. Merge request to three.js will follow....
