### ISSUE TITLE
Why can't I load obj and MTL?

### ISSUE THREAD

**Issue by happytoTom** [kaisalmen/WWOBJLoader#34]
When I go to load the zip file 
![image](https://user-images.githubusercontent.com/12823965/35576694-9a0203ec-061a-11e8-9d3c-5e804bd8b7a0.png)
![image](https://user-images.githubusercontent.com/12823965/35577136-bb6ea034-061b-11e8-998a-72e4d053cb99.png)

but the jsZip is not working, i dont know how to solve? plz help me~
![image](https://user-images.githubusercontent.com/12823965/35577260-0e2c14c8-061c-11e8-8043-600d732d9146.png)

**Comment by kaisalmen** [comment]
@happytoTom zip loading is not available with `OBJLoader2` directly. Otherwise I would create a dependency to jszip. Loading from zip is only available in example `wwobjloader2stage` which requires some extra which you can of course re-use.

Does it work of if don't use a zip file and just directly load obj and mtl as done in example `wwobjloader2`?

Anyway, whenever you have a problem, please copy text wherever possible (e.g. from the console) and use screenshots only as lat resort. Are you able to share your code somewhere?
Thanks.

**Comment by happytoTom** [comment]
@kaisalmen lading is ok for obj and mtl, I just want to increase the speed of loading, because the model is very big, do you have good suggestions? About model Cutting.
thanks.

**Comment by kaisalmen** [comment]
@happytoTom you can just re-use what is done in example `wwobjloader2stage`. The relevant steps are here:
https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwobjloader2stage/WWOBJLoader2Stage.js#L279-L342
and
https://github.com/kaisalmen/WWOBJLoader/blob/master/test/wwobjloader2stage/WWOBJLoader2Stage.js#L415-L510
