### ISSUE TITLE
Got an error in webpack project: "ReferenceError: THREE is not defined"

### ISSUE THREAD

**Issue by linzaihui** [kaisalmen/WWOBJLoader#50]
Hello. I'm working on a webpack project to load and render 3d model , and try to integrate wwobjloader2. But I got an error in chrome console: "ReferenceError: THREE is not defined".
![image](https://user-images.githubusercontent.com/26833023/69700820-60484580-1126-11ea-8220-0820c868f120.png)

What I did is following:

1. npm install three
2. npm i --save three-obj-mtl-loader
3. npm install wwobjloader2
4. add code `import OBJLoader2 from 'wwobjloader2'`

Help me please.

**Comment by Cobertos** [comment]
You don't need to install `three-obj-mtl-loader` and `wwobjloader2`. Those both exist in the `three` package file tree at `three/examples/js`.

What you need to do is use the webpack `imports-loader` to load any file in `three/examples/js`.

1. `npm install imports-loader`
2. Add a rule to your webpack config `module.rules` to use `imports-loader` to set the global variable `THREE` to `require('three')` so that scripts in the examples folder work. The rule looks like:

```
{
    test : /three[\\\/]examples[\\\/]js/,
    loader : "imports-loader?THREE=three"
}
```

3. In your project, do

```
import "three/examples/js/loaders/LoaderSupport.js"; //Loads to THREE.LoaderSupport
import "three/examples/js/loaders/OBJLoader2.js"; //Loads to THREE.OBJLoader2
import "three/examples/js/loaders/MTLLoader.js"; //Loads to THREE.MTLLoader
```

(You might need a `node_modules/` in front of `three` in the import statements above but I don't think so. I'm on my phone and can't check.)

When loaded they'll add their properties to the global `THREE` object which is the cached module object from `require('three')`. You should not be able to use them like normal from `THREE.OBJLoader2`.

https://github.com/Cobertos/ralsei-shader-test
This project uses a similar setup, but I believe it uses `GLTFLoader` instead. The webpack config is in `gulpfule.js`. You can look through it for reference if you'd like.

**Comment by linzaihui** [comment]
3q, solved.
