### ISSUE TITLE
npm ERR! peer three@"^0.129.0" from wwobjloader2@4.0.0

### ISSUE THREAD

**Issue by draibolit** [kaisalmen/WWOBJLoader#58]
I currently need the new feature in three@r133 and updated the package from the three@r122.
Then npm raised the error as the title.
Do you have any idea of how to solve it? 
Thank you!

**Comment by kaisalmen** [comment]
Hi, defining three as `peerDependency` version `^0.129.0` seems to be too restrictive. I need to fix this and release a new minor version with updated dependencies and move three from `peerDependencies` to `dependencies` for both `wwobjloader` and `three-wtm`

**Comment by kaisalmen** [comment]
Thank you for reporting this.

**Comment by kaisalmen** [comment]
I have just released: https://www.npmjs.com/package/wwobjloader2/v/4.0.1

**Comment by geoff-harper** [comment]
Moving this from peer to deps is causing duplication issues now. Three is throwing multiple instance warnings because the loader is using its own instance while we import our own for our uses. The OP should have worked around this or waited until wwobjloader updated the peer version. I'm not sure what the issue was anyways since 133 is in fact >129

**Comment by geoff-harper** [comment]
Hey Kai sorry for the delayed response, I think I muted github notifications by mistake. I tried the beta version and the install worked like a charm. I think `three` shojuld probably be a dev dep but at the end of the day it only installed my one version of three (I tried r143) and left r144 out so I'd say we're cooking. Thanks for the work you've put in to these, saved me when they removed the loaders from core
