### ISSUE TITLE
three.js versioning in package file

### ISSUE THREAD

**Issue by geoff-harper** [kaisalmen/WWOBJLoader#65]
I was wondering if `three` could be made a peer dependency? I am unable to use the latest version and I've locked it in at 0.128.0. The library functions but I have two versions installed. Would it continue to work on 0.128.0 instead of the current 0.133.1?

**Comment by kaisalmen** [comment]
Wouldn't i t make more sense to define three-js like `^0.128.1` and only upgrade it if the api / base class changes. I think there was a change needed after 128, that's why it is at `0.133.1`` , but I don't remember exactly right now. Next jump will be to be to 137+ (import maps) once I have finished the work on `three-wtm`.

**Comment by geoff-harper** [comment]
The version in question isn't the issue, it's that WWOBJLoader requires three as a regular dependency instead of a peer, so the three that is in this package file is also installed separately from the three in my package file. It would be more practical if this library included three as a peer+dev

**Comment by kaisalmen** [comment]
> It would be more practical if this library included three as a peer+dev

Ok, got it. That makes sense.

**Comment by geoff-harper** [comment]
I guess same goes for `three-wtm` as well since it looks to be the same setup. Thanks again for the work on these loaders, they sure beat me clumsily hand rolling my own

**Comment by kaisalmen** [comment]
@geoff-harper I consider this resolved. 5.0.0 will be released soon. #68 needs to be implemented, then it is should be ready.
