### ISSUE TITLE
name property of meshes not set

### ISSUE THREAD

**Issue by LeanderG** [kaisalmen/WWOBJLoader#8]
OBJLoader2 does not set the name property of the meshes it creates. The name stays an empty string.

OBJLoader on the other hand sets the name. Here is an example:
https://threejs.org/examples/?q=mtl#webgl_loader_obj_mtl
The name of the first mesh gets set to
`mesh1.002_mesh1-geometry_male-02-1noCullingID_male-02-1noCulling.JP`
which comes from the file `male02.obj` and from this line:
`g mesh1.002_mesh1-geometry_male-02-1noCullingID_male-02-1noCulling.JP`

I think OBJLoader2 should do the same.

**Comment by kaisalmen** [comment]
@LeanderG thanks, for spotting this. `WWOBJLoader2` did this correctly (all code before mesh creation is identical with `OBJLoader2`). What I realised when I looked at the code again is that object names overrule group names. It must be the other way around. Additionally, names after o, g, mtllib, usemtl where cut-off. This I fixed along.

I have updated the code on my website. [WWOBJLoader2Stage](https://kaisalmen.de/wwobjloader2/wwobjloader2stage/main.min.html) now prints names correctly (larger models otherwise to fast) along and mesh names are set correctly.
